name: Laravel CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laraveluser
          MYSQL_PASSWORD: laravelpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, bcmath, xml, curl, pdo_mysql
        coverage: none

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-scripts --no-interaction

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Configure database
      run: |
        sed -i "s/DB_CONNECTION=mysql/DB_CONNECTION=mysql/" .env
        sed -i "s/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/" .env
        sed -i "s/DB_PORT=3306/DB_PORT=3306/" .env
        sed -i "s/DB_DATABASE=laravel/DB_DATABASE=laravel/" .env
        sed -i "s/DB_USERNAME=root/DB_USERNAME=laraveluser/" .env
        sed -i "s/DB_PASSWORD=/DB_PASSWORD=laravelpass/" .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

