name: Deploy React to Vercel

on:
  push:
    branches:
      - main  # atau branch lain yang ingin kamu deploy otomatis

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend  # sesuaikan folder React kamu

    - name: Build React app
      run: npm run build
      working-directory: ./frontend  # sesuaikan folder React kamu

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}     # dapat dari Vercel project settings
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # dapat dari Vercel project settings
        working-directory: ./frontend
        prod: true

